// ──────────────────────────────────────────────────────────────────────────────
// AuraStore – Initial / Seed User Data
// ──────────────────────────────────────────────────────────────────────────────

import type { RegisteredUser } from './types';

export const INITIAL_REGISTERED_USERS: RegisteredUser[] = [
  {
    id: 'user-demo-1',
    name: 'Tawhid Namikaze',
    email: 'demo@aurastore.com',
    phone: '01712345678',
    password: 'password123',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Tawhid%20Namikaze',
    role: 'VIP',
    status: 'ACTIVE',
    joinedDate: '2026-01-15',
    isDemoUser: true,
    orderCount: 5,
    totalSpent: 14750,
    lastOrderDate: '2026-08-10',
    notes: 'Demo account – do not delete',
    addresses: [
      {
        id: 'addr-demo-1',
        fullName: 'Tawhid Namikaze',
        phone: '01712345678',
        streetAddress: 'House 42, Road 11, Banani',
        area: 'Banani',
        city: 'Dhaka',
        district: 'Dhaka',
        postalCode: '1213',
        country: 'Bangladesh',
        isDefault: true,
      },
    ],
  },
  {
    id: 'user-2',
    name: 'Ayesha Rahman',
    email: 'ayesha.rahman@gmail.com',
    phone: '01812345679',
    password: 'ayesha2026',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Ayesha%20Rahman',
    role: 'CUSTOMER',
    status: 'ACTIVE',
    joinedDate: '2026-02-03',
    orderCount: 3,
    totalSpent: 8900,
    lastOrderDate: '2026-07-22',
    addresses: [
      {
        id: 'addr-2',
        fullName: 'Ayesha Rahman',
        phone: '01812345679',
        streetAddress: 'Flat 3B, Lake Road',
        area: 'Dhanmondi',
        city: 'Dhaka',
        district: 'Dhaka',
        postalCode: '1209',
        country: 'Bangladesh',
        isDefault: true,
      },
    ],
  },
  {
    id: 'user-3',
    name: 'Mahir Chowdhury',
    email: 'mahir.c@yahoo.com',
    phone: '01912345680',
    password: 'mahir@secure',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Mahir%20Chowdhury',
    role: 'CUSTOMER',
    status: 'ACTIVE',
    joinedDate: '2026-03-18',
    orderCount: 1,
    totalSpent: 2499,
    lastOrderDate: '2026-06-01',
    addresses: [],
  },
  {
    id: 'user-4',
    name: 'Nusrat Jahan',
    email: 'nusrat.jahan@outlook.com',
    phone: '01612345681',
    password: 'nusrat2026!',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Nusrat%20Jahan',
    role: 'VIP',
    status: 'ACTIVE',
    joinedDate: '2026-01-28',
    orderCount: 8,
    totalSpent: 32400,
    lastOrderDate: '2026-08-20',
    notes: 'High-value repeat customer – priority support',
    addresses: [
      {
        id: 'addr-4',
        fullName: 'Nusrat Jahan',
        phone: '01612345681',
        streetAddress: 'House 7, Gulshan Avenue',
        area: 'Gulshan 2',
        city: 'Dhaka',
        district: 'Dhaka',
        postalCode: '1212',
        country: 'Bangladesh',
        isDefault: true,
      },
    ],
  },
  {
    id: 'user-5',
    name: 'Rakib Hassan',
    email: 'rakib.h@hotmail.com',
    phone: '01512345682',
    password: 'rakibpass99',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Rakib%20Hassan',
    role: 'CUSTOMER',
    status: 'BLOCKED',
    joinedDate: '2026-04-05',
    orderCount: 0,
    totalSpent: 0,
    notes: 'Blocked – chargeback dispute on order #AUS-0042',
    addresses: [],
  },
  {
    id: 'user-6',
    name: 'Sadia Islam',
    email: 'sadia.islam88@gmail.com',
    phone: '01712345683',
    password: 'sadia@123',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Sadia%20Islam',
    role: 'WHOLESALER',
    status: 'ACTIVE',
    joinedDate: '2026-02-20',
    orderCount: 15,
    totalSpent: 87600,
    lastOrderDate: '2026-08-25',
    notes: 'Wholesale buyer – 10% discount applied',
    addresses: [
      {
        id: 'addr-6',
        fullName: 'Sadia Islam',
        phone: '01712345683',
        streetAddress: 'Shop 12, New Market',
        area: 'New Market',
        city: 'Dhaka',
        district: 'Dhaka',
        postalCode: '1205',
        country: 'Bangladesh',
        isDefault: true,
      },
    ],
  },
  {
    id: 'user-7',
    name: 'Farhan Ahmed',
    email: 'farhan.ahmed@gmail.com',
    phone: '01812345684',
    password: 'farhan2026',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Farhan%20Ahmed',
    role: 'CUSTOMER',
    status: 'PENDING',
    joinedDate: '2026-08-28',
    orderCount: 0,
    totalSpent: 0,
    addresses: [],
  },
];
